/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bt;

import static bt.ControlPanel.jTable1;
import bt.PlannObject.AnyagHiany;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author gabor_hanacsek
 */
public class Anyaghiany extends javax.swing.JDialog {

    /**
     * Creates new form Allasido
     */
    PlannObject p;
    int x;
    int y;

    public Anyaghiany(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        createTable();
    }

    private void createTable() {
//itt csináljuk meg a tábla tulajdonságait
        TableColumn testColumn = jTable1.getColumnModel().getColumn(3);
        JComboBox<String> comboBox = new JComboBox<>();
//az inibol kell a lista, hogy milyen elemeket tartalmazzon a legordulo
        String[] lista = Variables.anyaghianylegordulo.split(",");
        comboBox.addItem("");
        for (String s : lista) {
            comboBox.addItem(s);
        }
//beallitjuk a culomba a cuccot
        testColumn.setCellEditor(new DefaultCellEditor(comboBox));

    }

    public void setVisible(PlannObject p, boolean b) {
        super.setVisible(b);
        this.p = p;
        getData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.95F);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Anyaghiány felvétele"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "PartNumber", "Tól (yyyy-MM-dd hh:mm)", "Ig (yyyy-MM-dd hh:mm)", "Felelős", "Komment", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(5).setMinWidth(30);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(30);
        }

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/close_1.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/save.png"))); // NOI18N
        jLabel2.setToolTipText("Adatok mentése");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/deleteallas.png"))); // NOI18N
        jLabel3.setToolTipText("Felvitt adat törlése");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(665, 313));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);

    }//GEN-LAST:event_jLabel1MouseClicked
//adatok kiszedese a plannobjectbol

    private void getData() {
        ArrayList data = null;
        data = p.getAnyaghianylista();
        //kinullazzuk az adatokat
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {

            for (int c = 0; c < model.getColumnCount(); c++) {

                model.setValueAt("", i, c);
            }

        }
        if (data != null) {

//beallitjuk az adatokat
            for (int i = 0; i < data.size(); i++) {
                PlannObject.AnyagHiany a = (PlannObject.AnyagHiany) data.get(i);
                model.setValueAt(a.pn, i, 0);
                model.setValueAt(a.tol.substring(0, a.tol.length()), i, 1);
                model.setValueAt(a.ig.substring(0, a.ig.length()), i, 2);
                model.setValueAt(a.felelos, i, 3);
                model.setValueAt(a.komment, i, 4);
                model.setValueAt(a.id, i, 5);
            }
        }

        jTable1.setModel(model);
    }


    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //anyaghiany mentese
        ment();


    }//GEN-LAST:event_jLabel2MouseClicked

    public void ment() {

//felvesszuk a tabla datait a plannobject tarolojaba
//leellenorizzuk, hogy megfeleloen van e kitoltve a tabla
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            String tol = "";
            try {
//a tol leellenőrzése
                tol = jTable1.getValueAt(i, 1).toString().trim();
//akkor megyünk tovább ha van tol dátum
                if (!tol.equals("")) {
                    if (!Pattern.matches("[0-9]{4}[-][0-9]{2}[-][0-9]{2}[ ][0-9]{2}[:][0-9]{2}", tol)) {
                        JOptionPane.showMessageDialog(p.getMainWindow(),
                                "Nem megfelelő dátum formátum a " + (i + 1) + " .sorban!",
                                "Hiba",
                                JOptionPane.ERROR_MESSAGE);
                        return;

                    }
//az ig leellenőrzése
                    String ig = jTable1.getValueAt(i, 2).toString().trim();
                    if (!Pattern.matches("[0-9]{4}[-][0-9]{2}[-][0-9]{2}[ ][0-9]{2}[:][0-9]{2}", ig)) {
                        JOptionPane.showMessageDialog(p.getMainWindow(),
                                "Nem megfelelő dátum formátum a " + (i + 1) + " .sorban!",
                                "Hiba",
                                JOptionPane.ERROR_MESSAGE);
                        return;

                    }

//a partnumber leellenőrzése
                    String pn = "";
                    try {
                        pn = jTable1.getValueAt(i, 0).toString().trim();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(p.getMainWindow(),
                                "Nem adtál meg pn-t a " + (i + 1) + " .sorban!",
                                "Hiba",
                                JOptionPane.ERROR_MESSAGE);
                        return;

                    }

//a felelős kitöltésének 
                    String felelos = jTable1.getValueAt(i, 3).toString();
                    if (felelos.equals("")) {
                        JOptionPane.showMessageDialog(p.getMainWindow(),
                                "Nem választottál ki felelőst a " + (i + 1) + " .sorban!",
                                "Hiba",
                                JOptionPane.ERROR_MESSAGE);
                        return;

                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(p.getMainWindow(),
                        "Nem megfelelő vagy hiányzó adatok!!",
                        "Hiba",
                        JOptionPane.ERROR_MESSAGE);
                return;

            }
        }
//ha eddig eljutottunk akkor kitörölhetjük a listát és felvihetjük az új adatokat
        p.clearAnyaghianylista();

        for (int i = 0; i < jTable1.getRowCount(); i++) {

            if (!jTable1.getValueAt(i, 3).equals("")) {

                String tol = jTable1.getValueAt(i, 1).toString().trim();
                String ig = jTable1.getValueAt(i, 2).toString().trim();
                String felelos = jTable1.getValueAt(i, 3).toString().trim();
                String pn = jTable1.getValueAt(i, 0).toString().trim();
                String komment = "";
                try {
                    komment = jTable1.getValueAt(i, 4).toString().trim();
                } catch (Exception e) {
                }
                String id = "";
                try {
                    id = jTable1.getValueAt(i, 5).toString().trim();
                } catch (Exception e) {
                }
                p.addAnyaghianylista(pn, tol, ig, felelos, komment, id);
            }

        }
//beállítjuk a tooltip textet
        p.formatText();
        p.repaint();

//az anyaghianyok rogzitese az adatbazisba
        String query = "insert ignore tc_anyaghiany (pktomig,pn,comment,felelos,tol,ig,cella, idtc_anyaghiany) values";
        String adatok = "";

        //bejarjuk a plannobjecteket es ha nagyobb az allasidos lista nullanal begyujtjuk az adatokat
        if (p.getAnyaghianylista().size() > 0) {

            for (int m = 0; m < p.getAnyaghianylista().size(); m++) {

                adatok += "(concat('" + p.getStartdate() + "', (select tc_becells.idtc_cells from tc_becells where tc_becells.cellname = '" + p.getbackendSheet().getName() + "'), (select tc_bestations.idtc_bestations from tc_bestations where tc_bestations.workstation = '" + p.getWorkStation() + "'), (select tc_bepns.idtc_bepns from tc_bepns where tc_bepns.partnumber = '" + p.getPn() + "'), '3', '" + p.getJob() + "'),'" + p.getAnyaghianylista().get(m).pn + "','" + p.getAnyaghianylista().get(m).komment + "','" + p.getAnyaghianylista().get(m).felelos + "','" + p.getAnyaghianylista().get(m).tol + "','" + p.getAnyaghianylista().get(m).ig + "','" + p.getbackendSheet().getName() + "','" + p.getAnyaghianylista().get(m).id + "'),";

            }

            adatok = adatok.substring(0, adatok.length() - 1);
            PlanConnect pc = null;
            try {
                query = query + adatok + "on duplicate key update comment = values(comment), felelos = values(felelos), tol = values(tol), ig = values(ig), pn = values (pn)";
                pc = new PlanConnect();
                pc.feltolt(query);
//visszakérdezzük
                query = "select * from tc_anyaghiany where pktomig = concat('" + p.getStartdate() + "', (select tc_becells.idtc_cells from tc_becells where tc_becells.cellname = '" + p.getbackendSheet().getName() + "'), (select tc_bestations.idtc_bestations from tc_bestations where tc_bestations.workstation = '" + p.getWorkStation() + "'), (select tc_bepns.idtc_bepns from tc_bepns where tc_bepns.partnumber = '" + p.getPn() + "'), '3', '" + p.getJob() + "')";
                pc.lekerdez(query);
                DefaultTableModel model = new DefaultTableModel();
                model = (DefaultTableModel) jTable1.getModel();
                for (int i = 0; i < model.getRowCount(); i++) {

                    for (int c = 0; c < model.getColumnCount(); c++) {

                        model.setValueAt("", i, c);
                    }

                }
                p.clearAnyaghianylista();
                int i = 0;
                while (pc.rs.next()) {

                    model.setValueAt(pc.rs.getString("pn"), i, 0);
                    model.setValueAt(pc.rs.getString("tol").substring(0, pc.rs.getString("tol").length() - 5), i, 1);
                    model.setValueAt(pc.rs.getString("ig").substring(0, pc.rs.getString("ig").length() - 5), i, 2);
                    model.setValueAt(pc.rs.getString("felelos"), i, 3);
                    model.setValueAt(pc.rs.getString("comment"), i, 4);
                    model.setValueAt(pc.rs.getString("idtc_anyaghiany"), i, 5);
                    p.addAnyaghianylista(pc.rs.getString("pn"), pc.rs.getString("tol"), pc.rs.getString("ig"), pc.rs.getString("felelos"), pc.rs.getString("comment"), pc.rs.getString("idtc_anyaghiany"));
                    i++;

                }

                jTable1.setModel(model);
//default title and icon
                JOptionPane.showMessageDialog(p.getMainWindow(),
                        "Sikeres mentés!");

            } catch (Exception e) {
                e.printStackTrace();
                Starter.e.sendMessage(e);
            } finally {
                try {
                    pc.kinyir();
                } catch (Exception e) {
                }
            }
        }

    }


    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        this.setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // anyaghiany torlese
        //allasido torlese
        //kitöröljük az adatbázisból
        PlanConnect pc = null;
        String query = "delete from tc_anyaghiany where tc_anyaghiany.idtc_anyaghiany = '" + jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString() + "'";
        try {
            pc = new PlanConnect();
            pc.feltolt(query);
            //visszakérdezzük
            query = "select * from tc_anyaghiany where pktomig = concat('" + p.getStartdate() + "', (select tc_becells.idtc_cells from tc_becells where tc_becells.cellname = '" + p.getbackendSheet().getName() + "'), (select tc_bestations.idtc_bestations from tc_bestations where tc_bestations.workstation = '" + p.getWorkStation() + "'), (select tc_bepns.idtc_bepns from tc_bepns where tc_bepns.partnumber = '" + p.getPn() + "'), '3', '" + p.getJob() + "')";
            pc.lekerdez(query);

            DefaultTableModel model = new DefaultTableModel();
            model = (DefaultTableModel) jTable1.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {

                for (int c = 0; c < model.getColumnCount(); c++) {

                    model.setValueAt("", i, c);
                }

            }
            p.clearAnyaghianylista();
            int i = 0;
            while (pc.rs.next()) {

                model.setValueAt(pc.rs.getString("pn"), i, 0);
                model.setValueAt(pc.rs.getString("tol").substring(0, pc.rs.getString("tol").length() - 5), i, 1);
                model.setValueAt(pc.rs.getString("ig").substring(0, pc.rs.getString("ig").length() - 5), i, 2);
                model.setValueAt(pc.rs.getString("felelos"), i, 3);
                model.setValueAt(pc.rs.getString("comment"), i, 4);
                model.setValueAt(pc.rs.getString("idtc_anyaghiany"), i, 5);
                p.addAnyaghianylista(pc.rs.getString("pn"), pc.rs.getString("tol"), pc.rs.getString("ig"), pc.rs.getString("felelos"), pc.rs.getString("comment"), pc.rs.getString("idtc_anyaghiany"));
                p.formatText();
                i++;

            }

            jTable1.setModel(model);
            //default title and icon
            JOptionPane.showMessageDialog(p.getMainWindow(),
                    "Sikeres törlés!");

        } catch (Exception e) {
            e.printStackTrace();
            Starter.e.sendMessage(e);
        } finally {
            try {
                pc.kinyir();
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anyaghiany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anyaghiany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anyaghiany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anyaghiany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Anyaghiany dialog = new Anyaghiany(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
